inherit_from: .rubocop_todo.yml

Style/IndentationWidth:
  Width: 2

Layout/SpaceAroundOperators:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  EmptyLinesAroundBlockBody:
    - when: always
